on: [push, pull_request]
name: Build
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install package
      run: |
        sudo apt-get update -y; sudo apt-get -y install libgtk-3-dev
      if: runner.os == 'Linux'
    - name: Build
      run: go build
      working-directory: iup

  test-gl:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install packages
      run: |
        sudo apt-get update -y; sudo apt-get -y install libgtk-3-dev libgl1-mesa-dev
    - name: Build
      run: go build -tags gl
      working-directory: iup

  test-motif:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install packages
      run: |
        sudo apt-get update -y; sudo apt-get -y install libmotif-dev libxmu-dev libxpm-dev
    - name: Build
      run: go build -tags motif
      working-directory: iup

  test-gtk2:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install packages
      run: |
        sudo apt-get update -y; sudo apt-get -y install libgtk2.0-dev
    - name: Build
      run: go build -tags gtk2
      working-directory: iup

  test-macos-gtk:
    runs-on: macos-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install package
      run: |
        brew install gtk+3
    - name: Build
      run: go build -tags gtk
      working-directory: iup
